### GET all Leagues
GET http://localhost:3000/api/leagues


### GET all teams of Bundesliga 
GET http://localhost:3000/api/teams

### GET teams by name 
GET http://localhost:3000/api/teams/Augsburg 


### GET team details 

GET https://www.thesportsdb.com/api/v1/json/1/lookuptable.php?l=4331&s=2020-2021